- bar.go
- barwidget_test.go
- internal/fdo_test.go
- internal/macos_test.go
- theme/gen.sh
- theme/maximize.svg
- theme/minimize.svg
- theme/theme.go
- wm.go
- wm/border.go
- wm/client.go
- wm/desk.go
- wm/frame.go
- wm/property.go
- wm/stack.go
- wm/stack_test.go
This refactors the wm to have another layer: client. It exists between the wm and the frame to manage windows, their hints, messaging, and properties. This also adds a minimize and maximize button with according functionality to the border. Finally, this fixes the appBar taskbar to work as a proper taskbar with the new features.
> Client refactor

- wm/client.go
- wm/desk.go
- wm/property.go
> Use messages to focus and follow _NET_ACTIVE_WINDOW spec.

- wm/client.go
- wm/desk.go
Then apply on client creation.
Fixes #31
> Add hints to the window on client message if a client doesn't exist yet

- wm/client.go
- wm/desk.go
- wm/frame.go
This can be seen via chrome/chromium.  In settings toggle Use system titlebar/borders.
> Improve handling of borderless windows and hotswapping borders.

- barwidget_test.go
- wm.go
- wm/client.go
- wm/desk.go
- wm/frame.go
- wm/stack_test.go
> Implement click to focus.  Clicking anywhere on a window raises+focuses it now.

- bar.go
- barwidget_test.go
- go.mod
- go.sum
- internal/fdo_test.go
- wm.go
- wm/border.go
- wm/client.go
- wm/frame.go
- wm/property.go
- wm/stack_test.go
> Use the window icon first when choosing border/taskbar icons.

- wm/client.go
- wm/desk.go
- wm/frame.go
This fixes the drawing, moving, resizing of gnome apps, as well as mouse wheel on gnome apps.
> Fix gnome apps to work with fynedesk frames

- wm/desk.go
- wm/frame.go
- wm/property.go
This follows the icccm spec and also fixes applications like terminology.
> Adjust windows according to their desired increment.  Notify windows when their size changes

- bar.go
- barwidget_test.go
- desk_test.go
> Refactor tests to no longer need a full desktop implementation

- wm/desk.go
- wm/frame.go
Fixes windows that weren't getting click to focus after iconification.
> Fix click to focus for windows - primarily after iconification

- internal/fdo.go
- internal/fdo_test.go
- internal/ui/bar.go
- internal/ui/baricon.go
- internal/ui/barwidget_test.go
For items in the bar offer to remove them, if not then offer to pin them to the launcher.
> Add a handy add/remove menu

- internal/ui/launcher.go
- internal/ui/launcher_test.go
- internal/ui/settings_ui.go
Updated the app bar tab in settings to be in a single tab with a rather more intuitive UI
> Update app bar settings screen - down to a single tab

- wm.go
- wm/client.go
- wm/desk.go
- wm/events.go
- wm/frame.go
- wm/property.go
- wm/screens.go
- wm/stack.go
- wm/stack_test.go
- wm/switcher.go
Factor out event code in wm to events.go
Order functions based on:
--All public functions in alphabetical order
--All public methods in alphabetical order
--Remaining methods/functions in alphabetical order
> Clean up WM package

- wm/border.go
- wm/client.go
- wm/desk.go
- wm/events.go
- wm/frame.go
Liven things up a bit :)
Added a cache of the focus state as well, seemed like a small optimisation that could help
> Colour borders based on border status

- wm/border.go
- wm/desk.go
- wm/events.go
- wm/frame.go
- wm/property.go
This fixes size constraints such as min size, max size, and fixed size when resizing windows.
Fixes #85 and #86
> Size Fixes

- modules/builtin/battery.go
test if charge files exist before using them, for lenovo laptops we should use energy files
> fix battery value on laptop

- modules/builtin/battery.go
- modules/builtin/brightness.go
Quieten brightness and battery on desktop
Fixes #120
> Silently fail if standard errors

- cmd/fynedesk_runner/log.go
- cmd/fynedesk_runner/main.go
makes "fynedessk-crash-<date>.log" files alongside fynedesk.log when it detects a crash.
> Copy log files out to crash logs when something goes wrong

- internal/x11/win/frame.go
- wm/border.go
This is an attempt at handling double click to maximize/unmaximize using go's Context api.
Addresses #125
> Add the ability to maximize/unmaximize windows by double clicking titlebar

- .gitignore
- Makefile
Also makes sure that binaries are ignored by git.
> Clean up Makefile and check for destdir

- Makefile
Nothing fancy. Just a simple way to uninstall FyneDesk in case anyone wants to do so.
> Add an uninstall target to the Makefile

- internal/ui/settings.go
- internal/ui/settings_ui.go
- internal/ui/widgetpanel.go
- settings.go
- test/settings.go
This PR adds support for changing between 12h and 24h time (12h is default).
> Add option to use 24h time (also fixes 12h time)

- go.mod
- internal/ui/bar.go
- internal/ui/desk.go
- internal/ui/desk_embed.go
- internal/ui/desk_full.go
- internal/ui/desk_test.go
- internal/ui/widgetpanel.go
- internal/x11/win/client.go
- internal/x11/wm/desk.go
- internal/x11/xwm.go
This speeds up load and reconfigure.
Seems more stable for the screen configuration too.
> Update multiple roots to only control Primary with Fyne

- internal/ui/about.go
- internal/ui/background.go
- internal/ui/bar.go
- internal/ui/desk.go
- internal/ui/launcher.go
- internal/ui/notifications.go
- internal/ui/settings_ui.go
- internal/ui/widgetpanel.go
- internal/x11/wm/events.go
- modules/status/battery.go
- modules/status/brightness.go
- modules/status/sound.go
Fixes a bunch of deprecated function usages.
> Make staticcheck happy for the fyne 2.0 update

- internal/ui/background.go
This removes an unused import.
> Fix unused import in internal/ui/background.go

- .github/workflows/platform_tests.yml
- .github/workflows/static_analysis.yml
Same as https://github.com/fyne-io/fyne/pull/1850.
> Remove unnecessary golang install in ci

- internal/x11/cursor.go
- internal/x11/win/frame.go
Just a narrow strip, avoiding buttons.
FIxes #113
> Allow resize from top corners

- desk.go
- internal/ui/desk.go
- internal/ui/desk_embed.go
- internal/ui/desk_full.go
- internal/ui/embed_wm.go
- internal/ui/widgetpanel.go
- internal/x11/win/client.go
- internal/x11/wm/desk.go
- internal/x11/wm/events.go
- test/desktop.go
- wm.go
Appears and works, but does not dismiss unless clicked.
Possible solutions one of the following:
Fixes #128
> Render menu over windows

- internal/ui/desk.go
- internal/x11/wm/desk.go
- internal/x11/wm/events.go
- internal/x11/wm/stack.go
- internal/x11/wm/switcher.go
Problem was visible when all windows were closed - was a focus issue.
Fixes #160
> Move key bindings from Alt to Super and fix issue when they could stop working

- internal/ui/launcher.go
- modules/status/brightness.go
- modules/status/sound.go
- modules/status/sound_bsd.go
- modules/status/sound_other.go
- modules/status/sound_test.go
Add volume controls.
Fixed some volume bugs as well.
> Add status commands to launch window

- internal/ui/desk.go
- internal/ui/settings.go
- internal/ui/settings_ui.go
- internal/x11/wm/desk.go
- internal/x11/wm/events.go
- keys.go
- settings.go
- test/settings.go
Just what it says, allow users to choose Alt for their standard key bindings instead of Super.
> Make modifier Alt/Super a user preference

- Makefile
- README.md
Fixes the release badge and makes sure that it points to the latest release. Removes some unnecessary stuff in the makefile as well.
> Fix some old leftovers

- internal/x11/wm/desk.go
Main menu can not show in embed mode. Position error due to height error.
> Fix the bug of main menu display position when Runner is not used

- modules/launcher/calc.go
I cleaned up the code to only compile the regular expressions once instead of on each new module creation.
> Clean up the calculator module

- internal/ui/desk.go
- internal/x11/wm/desk.go
- keys.go
Maybe this should be configurable - probably in some default apps area we will add later
> Add a keyboard shortcut to open calculator

- CHANGELOG.md
- internal/ui/widgetpanel.go
- internal/x11/win/client.go
- internal/x11/wm/desk.go
- test/window.go
- window.go
- wm/border.go
Required tidying up some missing position handle code, all feeling a bit neater.
> Add a basic window menu

- README.md
Jury's still out on the Oxford comma
> Spelling, grammar, and deference toward Oxford commas.

- CHANGELOG.md
I should have cough this sooner, but I noticed that there were two relatively important mentions that didn't manage to get onto the changelog. Either way, it should now be there before the full release is published on GitHub (not within the tag though).
> Add two missing changes to changelog

- .github/workflows/platform_tests.yml
- .github/workflows/static_analysis.yml
These are basically equivalent except for using Go 1.16 for static analysis still as I don't have 1.17 to commit the new format for build constraints.
> Update workflows against upstream Fyne

- README.md
This improves the docs for dependencies making them clearer as well as better noting down compile/runtime deps.
Fixes #221
- [-] Tests included.
> Add better documentation of compilation dependencies

- internal/ui/widgetpanel.go
> Use idiomatic go to retrieve user full name

- modules/systray/main.go
Basic notification monitor and update icon on change...
> Update systray icon when it changes
