FyshOS/fynedesk

bar.go
barwidget_test.go
internal/fdo.go
internal/fdo_test.go
internal/testdata/applications/app3.desktop
wm.go
wm/client.go
wm/desk.go
wm/property.go
wm/stack_test.go

This adds a missing icon when a .desktop match can not be found so that windows without matches still appear on the taskbar.  It also introduces hint handling for _NET_WM_SKIP_TASKBAR and sets this hint  on the root window children so that they skip the taskbar.

Missing icon

---

wm/client.go
wm/desk.go
wm/frame.go

Chromium, gtk3, and others use their own borders and titlebars and request movement and resizing via extended window manager hints.  This handles those hints to allow the window manager to move and resize those windows.
Fixes #23

Add the ability to move and resize windows not using Fyne borders.

---

wm/client.go
wm/desk.go
wm/frame.go
wm/property.go

This fixes the "flicker" that was seen when windows were initially set to fullscreen where the window would show up for a second and then go fullscreen.
This also now handles the property change notify hint so that we can start updating window properties as they change.  The first step is to update the window title when the name changes.

Clean up initial fullscreen and update border when title changes

---

cmd/fynedesk/main.go
cmd/fynedesk/main_linux.go
desk.go
desk_test.go
screen.go
wm/client.go
wm/desk.go
wm/frame.go
wm/property.go
wm/screens.go
wm/stack.go

This supports configurable primary screens, user defined scaling, auto scaling, and fixes a lot of issues with apps such as gnome apps.
The one caveat here is that there is one scale value across all monitors, rather than being calculated per monitor.  This will need to be addressed in the future.
Fixes #27

Implement XRandR Multihead Support - Fix Gnome Apps - Scale Desktops

---

internal/notify/mouse.go
wm/desk.go
wm/frame.go
wm/property.go

A few bug fixes for release -
We only want to manage certain windows regardless of whether have the transient property, so the transient check was useless and actually messed up a few menus that didn't have transient set but had window type menu set.
Fix lint warning on MouseNotify interface.
Borderless windows need the synthetic configure notify as well decorated ones.  Refactoring out the synthetic notify to be in the release function of frame broke borderless windows getting updated correctly.  This fixes that.

Transient fix, lint fix, and configure notify fix

---

wm/frame.go

Raise the window to the top before hiding to ensure that it is on top of the stack so we can walk the stack list backwards to find the next available window, that is not iconified, to focus.

Fix focusing windows after iconifying.

---

internal/ui/desk_test.go
internal/ui/launcher.go
internal/ui/launcher_test.go
internal/ui/widgetpanel.go
wm/desk.go

This adds a "selected app" in the list as well as the keyboard bindings:
* Alt-space to open launcher
* Escape to close it
* Enter will launch the selected app
* Up and down will change the app selected
Also new tests are added which is easier with the refactored code.

Add key bindings for app launcher

---

wm/client.go
wm/desk.go
wm/events.go
wm/property.go
wm/transient.go

Initially we had turned SubstructureNotify on for the root window - This is incorrect as we were picking up things like map request events from clients that were not managed by us and shouldn't be managed by us and thus managing those clients incorrectly.
Introduces transient handling and colormap handling.

This fixes several issues related to colormaps and client map requests

---

internal/ui/desk.go
internal/ui/desk_test.go
wm/desk.go

Turns out QT_SCALE_FACTOR is not reliable below 1.
This ensures value is neer below 1
https://www.reddit.com/r/kde/comments/a54rul/how_to_set_scaling_to_below_100/
> Qt itself doesn't work with scale factors < 1. Try QT_SCALE_FACTOR=0.75 kcalc.

Fix QT App corruption

---

cmd/fynedesk_runner/log.go
cmd/fynedesk_runner/log_darwin.go
cmd/fynedesk_runner/log_test.go
cmd/fynedesk_runner/log_unix.go
cmd/fynedesk_runner/log_windows.go
cmd/fynedesk_runner/main.go

Attempts to use system locations for the log file.
If you run the fynedesk app directly it will still log to console.

Set up some default logging in the runner

---

internal/ui/widgetpanel.go
internal/x11/wm/desk.go

We should have been closing all windows - a bug in WidgetPanel hid that, fixed
W now give windows 10 seconds, then show a notification.
Dialog was an alternative but the fyne dialog API is not easy for us as it relies on an open window (easier with compositor)
Fixes #92

Wait for all clients to shut down before we exit

---

internal/x11/win/frame.go
wm/border.go
wm/button.go
wm/util.go

Removing X specific maths heavy code and instead use the Fyne border code better.
This moves cursor and tap handling into Fyne code (/wm/border.go) as you would have expected.

Refactor border logic to border

---

internal/x11/win/client.go

When a window doesn’t request its position we can move it.
But when we are restarting we should not.
This change means that positioned windows will be left.

Fix for windows moving to 0,0 on restart

---

internal/x11/wm/desk.go
internal/x11/wm/events.go

This was an issue when we had just 1 screen
because the re-configure did not arrive with only a single root
Fixes #114

Fix for Java Swing windows being 0 sized

---

Makefile

The following changes have been made to improve it:
- We follow common practice and set PREFIX, not DESTDIR.
- Go builds into current directory. Use correct install rules for that (I have honestly no idea why it worked before).
- We now use the install command with correct file permissions for binaries and text files and option to create directories if not existing.
The result of all this is that the Makefile is now complying with building `fynedesk` inside `solbuild`, the containerized packaging solution for Solus. I have thus successfully built and installed a `fynedesk` package built for solus as `fynedesk-0.1.3-1-1-x86_64.eopkg`. Not in any repository, but great nun the less :)
For anyone interested, here is the package.yml file for it:
```yml
name       : fynedesk
version    : 0.1.3 …
```

Update and improve Makefile to use better install practices

---

internal/ui/settings_ui.go

This commit changes the starting location of the file dialog that selects the background to try to use the pictures folder.
It also filters out files to only show jpg/jpeg, png and svg.

Filter background image selction and default to pictures dir

---

Makefile
README.md

I am tired of copy-and-pasting the lines from the README whenever I want to do this. Now we can just run `make run -j2` to do it :)

Add a way of running in embedded X window using make

---

internal/ui/screenshot.go

Below is a list with the changes:
- A "screenshot.png" filename is now preset when saving.
- The default folder for saving is now the Pictures dir (if found).
- The file is now propertly closed after being saved.
- Various code cleanups for readability.

A few improvements to the screenshot shower

---

internal/x11/win/client.go
internal/x11/win/frame.go
internal/x11/wm/desk.go
internal/x11/wm/events.go
internal/x11/xwin.go
test/window_x11.go

Don't propogate mouse clicks on moveresize events
Don't send a configure after moveresize cancel
Fixes #163 and #119

Use a queue to configure windows on move/resize.

---

internal/x11/win/frame.go

Following @okratitan advice I've updated the buffer of the queue and now it's quite faster on moving windows

Increase buffer to improve moving windows velocity

---

.github/workflows/static_analysis.yml

Basically the same as https://github.com/fyne-io/fyne/pull/1978
This updates the static analysis to use Go 1.16 for the improvements with using go install with a version number (only used for staticcheck for now as it receives a lot of updates and just pulling latest might break us). It also allows it to be used without modifying go.mod (thus not needing to turn off modules each time). Go 1.16 also has a slightly faster linker so the installation and build of the ci tools should be a bit faster.
It also switches to a faster go setup action which is about three times faster while also allowing us to see inline staticcheck reports in PR diffs (cool stuff). Only doing this for static analysis for now as I can't get it to past for the platform tests just yet.
I also made sure to tell …

Improved static ci

---

internal/icon/fdo.go

This lets the default pinned terminal pick up fyneterm as an option if it is installed on the system.
If it is not, it will fall back to the other common terminals that might exist.

Allow fyneterm to be picked up automatically

---

internal/x11/win/frame.go

This commit applies the work done by running `unconvert -apply ./...` on the codebase in order to remove unnecessary conversions. It only happened in two places on the same line, so this very minor PR just fixes that little case :)

Remove unnecessary type convertions

---

internal/icon/fdo.go
internal/ui/desk.go
internal/ui/settings_ui.go
internal/x11/wm/desk.go
modules/status/brightness.go
modules/status/sound.go
modules/status/sound_bsd.go

This switches to strconv where it is possible to do so without severely hurting readabilty and where it generally makes sense.
Performance and memory usage should generally be slightly better than before in these cases and there were even two cases for the sound module, where I managed to remove the convertions entirely.

Switch from fmt.Sprintf to strconv where useful

---

internal/x11/win/frame.go
wm/position.go
wm/position_test.go

When a window has no specified position the top left is not most helpful, move to middle for now (smarter algorithms could be added later).

Fix default position to middle not topleft

---

internal/x11/win/client.go
test/window.go
test/window_x11.go
window.go
wm/position.go
wm/position_test.go

This also fixes positioning of windows inside active screen when not top/left monitor
Fixes #48

Position windows that are transient inside their parent

---

modules/composit/compton.go

Fixes screen tearing on OpenBSD (tested: 7.2-beta, amdgpu) and potentially on other platforms, by forcing compton to use drm as vsync method.

Forcing vsync to be enabled by default

---

internal/ui/bar.go
internal/ui/bar_test.go
internal/ui/widgetpanel.go

As suggested we can remove the icon from the menu and put it with apps where it belongs

Move the search button to the first app icon

---

Makefile

Using a multi-monitor setup of GNOME [1]; The Xephyr embedded Fynedesk session (called by `make embed`) reliably crashes the host window-manager. GNOME recovers from this -- Xephyr launches and connects to Fynedesk, but this results in Fyne defined elements like the 'search box', 'application menu', and any resulting apps to be launched on the host and not in said embedded session.
This PR makes two edits to the 'embed' section of the Makefile; Namely, by dropping the first explicit deceleration of the DISPLAY variable. This should be set by one's host anyways & hard-coding it seems to cause problems at least in this given usecase.  And the second edit, is switching the given display server port to a less often used value; It was suggested we use :2 or :5. Ultimately, :5 was chosen …

Fix Xephyr support in multi-monitor GNOME setups.

---

AUTHORS
go.mod
go.sum
internal/ui/about.go
internal/ui/bar.go
internal/x11/win/client.go
internal/x11/win/frame.go
internal/x11/wm/desk.go
internal/x11/wm/events.go
internal/x11/wm/stack.go
internal/x11/wm/switcher.go
modules/desktops/desktops.go
modules/desktops/pager.go
test/window.go
window.go
wm.go

They fill the space available according to window size.
It fills. Could be adjusted to fit in the center if folk prefer to maintain aspect ratio.

Add icons to desktop pager

---

cmd/fynedesk/main.go
go.mod
go.sum
internal/ui/desk.go
internal/x11/win/client.go
internal/x11/wm/desk.go
modules/desktops/pager.go
modules/quaketerm/init.go
modules/quaketerm/term.go
test/window.go
window.go

Last feature addition for v0.4 I think :)
https://github.com/FyshOS/fynedesk/assets/294436/6dab63c2-0e55-4caa-a492-25b03318de47

Add quake mode terminal module
